## https://github.com/marketplace/actions/gh-actions-stale-run-canceller
## File: .github/workflows/shot.yml
name: build_canceller
on:
  push:
jobs:
  build_canceller:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: shot
      uses: yellowmegaman/gh-build-canceller@v1.6
      with:
        github_token: ${{secrets.PERSONAL_TOKEN}}
        workflows_filter: "CI|pr"
